#!/usr/bin/perl -w

# Launches sz in server mode, then causes rzh to connect and download
# the file(s).


my $sendfile = 'tt.c';
my $dstdir = '/tmp';
my $loglevel = 6;

-f $sendfile or die "$sendfile does not exist!\n";

open($sz, "sz --tcp-server $sendfile |");
while(<$sz>) {
	if(/connect with lrz --tcp-client "([^"]+)"/) {
		exec "./rzh $dstdir --connect $1 --log-level $loglevel\n";
	}
}

