#!/usr/bin/perl -w

# Launches sz in server mode, then causes rzh to connect and download
# the file(s).

# Invoke as "fireup --valgrind" to run rzh under valgrind.


my $sendfile = 'rztask.h';
my $dstdir = '/tmp';
my $loglevel = 10;
my $logfile = '/tmp/rzh.log';

@rzh = ("./rzh");
if(grep { /^-v$/ || /^--valgrind$/ } @ARGV) {
	unshift @rzh, "/usr/bin/valgrind";
}

-f $sendfile or die "$sendfile does not exist!\n";
system("/bin/rm", "-f", $logfile);

open($sz, "sz --tcp-server $sendfile |");
while(<$sz>) {
	if(/connect with lrz --tcp-client "([^"]+)"/) {
		exec(@rzh, $dstdir, "--connect", $1,
			"--log-level", $loglevel, "--log-file", $logfile)
			or die "Could not exec rzh: $!\n";
	}
}

