#!/bin/sh

# make-dist (for rzh)
# Scott Bronson
# 30 May 2000 - 11 Nov 2004


name=$(basename $(pwd))
version=$(perl -ne '/VERSION=([0-9]+\.[0-9A-Za-z_.-]+)/ && print $1' Makefile)
# version=$(perl -MExtUtils::MakeMaker -le 'print MM->parse_version(shift)' 'lib/Term/GDBUI.pm')
# version=$1

if [ ! "$version" ] ; then echo "You must supply a version number." ; exit 1 ; fi

if grep -vw $version CHANGES 2>&1 >/dev/null; then echo -n
else echo echo "Did you update the Changelog?" ; exit 1 ; fi

pushd . 2>&1 > /dev/null

# Ensure tree is ready to go
make dist-clean > /dev/null || exit 1

# get rid of possible old files
rm -rf /tmp/$name-$version
rm -rf /tmp/$name-$version.tar.gz

# make a working copy in /tmp
cp -r . /tmp/$name-$version

# remove unneeded files
cd /tmp/$name-$version
find . -name .svn | xargs rm -rf
rm -f Makefile.old
rm make-dist

# check for any invisible files
find . | grep /\\. && echo "BAD FILES!  Won't finish." && exit 1

# check the version number on all modules
if ((0)) ; then
find . -path './t' -prune -o -name '*.pm' -print | while read file; do
	fver=$(perl -MExtUtils::MakeMaker -le 'print MM->parse_version(shift)' "$file")
	if [ "x$version" != "x$fver" ]; then
		echo "Versions don't match!  $file is $fver, should be $version."
		exit 1
	fi
done
fi
# bash is really weird
if [ "$?" != "0" ]; then exit 1; fi

# show a list of files so we can see questionable stuff
find .

# tar it up
cd ..
tar zcf $name-$version.tar.gz $name-$version

# we're done
echo "New dist is in /tmp/$name-$version.tar.gz, enjoy!"
popd 2>&1 > /dev/null

