=head1 NAME

B<rzh> - Receive ZMODEM Here

=head1 SYNOPSIS

The following example transfers the /etc/hosts file
on tt.asplode.com to the download directory on the local host.

  $ cd downloads
  $ rzh
  $ ssh tt.asplode.com
  $ sz /etc/hosts

=head1 DESCRIPTION

rzh sits in the background listening for a zmodem transfer request.
When it sees one, it springs to action and sucks down the file.
Other than downloading zmodem files, it will never get in your way.

=head1 OPTIONS

=over 8

=item B<-q>

TODO
Suppresses the printing of status messages.
Error messages are still printed to stderr.

=item B<-r>

Receives a file immediately into the current directory.
Effectively the same as the L<rz(1)> command.

=item B<-V>

Prints the version and exits.

=back

=head1 NOTES

If rzh is running as root, it will not mark downloaded files as executable.

To ensure that we don't mess up filenames in other character encodings,
we do not attempt to sanitize the filename.  This is a feature.
I'll fix this if somebody can show that's it's a security hazard.

We don't support directories in the filename.  If the sending program
includes directories (i.e. "a/b/file.ext"), we'll fail to create the file.

=head1 BUGS

The code is a lot more complex than it should be.  I first wrote this to
lrzsz, and when that didn't work, adapted the resulting monstrosity to pdpzm.
Things would be a lot simpler if I were to rewrite zio with coroutines.
Unfortunately, this probably won't happen in the near future.

=head1 SEE ALSO

L<rz(1)>, L<sz(1)>

=head1 LICENSE

Following pdpzm and sqlite's examples, rzh is placed into the public domain.

=head1 AUTHORS

=over 4

=item Scott Bronson <S<bronson@rinspin.com>>

=item zmodem code by Paul Edwards <S<kerravon@w3.to>>

=back

=cut
