=head1 NAME

B<rzh> - Receive ZMODEM Here

=head1 SYNOPSIS

B<rzh> [B<-q>|B<-v>] [I<directory>]

To transfer the /etc/hosts file on tt.asplode.com to the current directory.

  $ rzh
  $ ssh www.asplode.com
  $ sz /etc/hosts
  173 bytes sent in 0.3 seconds.
  $

=head1 DESCRIPTION

rzh forks itself ot the background and handles zmodem transfer requests.

rzh can be useful for copying files between directories on the
local machine.  Run rzh in the destination directory, then cd
to the source directory and send each file using sz.  This is
easier than specifying the full path every time.

=head1 OPTIONS

In the absence of B<-r> or B<-s>, rzh will fork itself to the background
and wait for a zmodem send request.

Specify the directory that you'd like to receive files to on the
command line.  If no directory is supplied, the current directory
is used.

=over 8

=item B<-h> B<--help>

Output a quick usage summary.

=item B<-q> B<--quiet>

Suppresses the printing of status messages.
Error messages are still printed to stderr.

=item B<-v> B<--verbose>

Increases verbosity.

=item B<-V> B<--version>

Prints the version and exits.

=item B<--rz>

Specifies the location and default arguments for the rz program.
By default rzh uses "/usr/bin/rz".  You can use aliases to specify
this argument by default (for instance, if you wanted to disable
timeouts):

	alias rzh="rzh --rz='/usr/bin/rz --no-timeout'"

You must specify the full path to the executable -- rzh doesn't
use the PATH variable.  Also, rzh doesn't currently support quoting
or backslashing in the
argument list.  --rz='rz --prompt="a b"' will fail because
"a b" will be interpreted as two separate arguments.  Short of
implementing a mini command-line parser in rzh, I don't see an easy way
around this.  Contact the author if you need this functionality.

=back

=head1 KEYS

rzh reads keyboard input while a transfer is going on.  Here are
the keys that it recognizes:

=over 4

=item ESC ^C q Q

Cancels the current transfer.

=head1 ENVIRONMENT

=over 4

=item SHELL

Specifies the shell that rzh should use.

=item RZHDIR

If you're currently running rzh, this specifies the full path
to the download directory.

=back

=head1 BUGS

rzh suffers from all rz/sz bugs.
For instance, with lrzsz, try calling sz with an invalid filename.
Sometimes it will print an error, sometimes it will hang.

=head1 SEE ALSO

L<rz(1)>, L<sz(1)>

=head1 AUTHOR

=over 4

=item Scott Bronson <S<bronson@rinspin.com>>

=back

=cut
